throw Error('my thrown error')
